const router = require('express').Router()
const usersRoutes = require('./users')
const reservationRoutes = require('./reservations')
const customersRoutes = require('./customers')
const roomRoutes = require('./rooms')
const currentDate = require('./currentDate')
const loginRoute = require('./login')
const logoutRoute = require('./logout')
const roomTypesRoutes = require('./roomTypes')
const reservationRoomsRoutes = require('../../routes/reservationRooms')
router.use('/login', loginRoute)
router.use('/logout', logoutRoute)
router.use('/users', usersRoutes)
router.use('/customers', customersRoutes)
router.use('/current', currentDate)
router.use('/reservations', reservationRoutes)
router.use('/reservation_rooms', reservationRoomsRoutes)
router.use('/rooms', roomRoutes)
router.use('/room/types', roomTypesRoutes)

module.exports = router
